spring:
  flyway:
    enabled: true
    locations: classpath:db/migration-local
    baseline-on-migrate: true
    baseline-version: 9
    user: ${DB_MIGRATION_USER}
    password: ${DB_MIGRATION_PASSWORD}
    placeholders:
      appRole: ${DB_APP_ROLE}
